### ISSUE TITLE
Failed to load interface for ‘Text.LaTeX.Base.Syntax’

### ISSUE THREAD

**Issue by luckypoem** [konn/konn-san.com#1]
hi.

root@AR:/usr/local/konn-san.com# ghc --make site.hs
[1 of 4] Compiling Lenses           ( Lenses.hs, Lenses.o )

Lenses.hs:9:1: error:
    Failed to load interface for ‘Text.LaTeX.Base.Syntax’
    Use -v to see a list of the files searched for.
root@AR:/usr/local/konn-san.com# 

how to fix it?
thank you!

**Comment by konn** [comment]
It's my web site. Don't compile...
